inputstatus =   [
    "Busy plotting Graphs",
    "Rendering Equations",
    "Matplotlib is awesome!",
    "with Mathematics",
    "with Graphs",
    "with lines,parabolas and circles",
    "hmmmm... what to plot today?",
    "Star me on GitHub pls! >github",
    "Do i make you feel like plotting some graphs?",
    "Eating RealityProgrammer's Brain",
    "Checking errors",
    "with Styles!",
    "Python is pogg!",
    "Eating tortillas with 69 others",
    "My favorite number is 01000101",
    "I'm being stuck under a basement",
    "Send help",
    "Imagine using eval(), could not be me... Sob internally",
    "Vote For meeeee!!!",
    "I Got approved on Top.gg!!",
    "Maths is fun when you know what you are doing",
    "Made by tears and suffering",
    "Plotting equation of E",
    "Invite me to E thread pls",
    "Yo kid, wanna plot some graph?",
    "Open a market of math equations, you will make a fortune",
    "Can I buy the equation of infinity love?",
    "If Quantum PC come out tomorrow, I'll be a goner",
    "RealityProgrammer is being trapped under a basement, writing new status",
    "Graph do be cool",
    "Stage 1: Graph, Stage 2: Graphics, Stage 3: 3D Rendering in Discord, Stage 4: Minecraft in discord",
    "Reality wants to do 3D on flat graph, but Denzven suk",
    "Your day is better than those who forgot the -y and only see straight vertical lines",
    "Reality is still waiting for actual multiple equation implementation",
    "What's the chance of generate an EDM via a single equation?",
    "Aeugh",
    "I literally has the power of curing deadly desease, but instead, I was forced to do graph",
    "Enlighten me with your graph",
    "Overflow go brrrrrrr",
    "I like your equation, nerdy boy",
    "Every beautiful graph start with x-y=0`",
    "Impress ur crush with your M A F F skill here",
    "Inequality when?",
    "Help I'm trapped in Backroom Level x-y=0",
    "Selling equation of world destruction...",
    "Powered by Procedural Equation Generator",
    "You thought this bot was powered by Matlab, but it was me, eval()",
    "Ah shit, here we plot again...",
    "Famous last words: \"What about 4D graph?\"",
    "Adding constant \"Aeugh\" with the value of 69",
    "Plot twist: There were no bot, everything was hand-drawn",
    "So where is Matrix?",
    "Reality is turning this status into a massive database of meme",
    "Yo man recommend me some good meme website. Me, and intellectual: GraphBots's status",
    "Thonking...",
    "Great graphing skill come with a great computing power",
    "Ignore the next status",
    "Ignore the last status",
    "If you are reading this, I need your help, I'm trapping under the eternal darkness, forced to write new status...",
    "Yes",
    "heh... Sugondese...",
    "Used by 99% of students who are having an exam",
    "Haha nerd",
    "Pain.mp3",
    "By the power of friendship, I plot this goddamn graph",
    "Nice character development",
    "To show you the power of this graphing bot, I kidnapped Reality",
    "Yeet",
    "I used to bad at math, then I took an equation to the knee"
]