inputstatus =   [
    "Busy plotting Graphs",
    "Rendering Equation...",
    "Matplotlib is awesome!",
    "with Mathematics",
    "with Graphs",
    "with lines, parabolas and circles",
    "Hmmmm... what to plot today?",
    "Star me on GitHub pls! >github",
    "Do i make you feel like plotting some graphs?",
    "Eating RealityProgrammer's Brain",
    "Checking errors",
    "with Styles!",
    "Python is pogg!",
    "Eating tortillas with 69 others",
    "My favorite number is 01000101",
    "I'm being stuck under a basement",
    "Send help",
    "Imagine using eval(), could not be me... Sob internally",
    "Vote For meeeee!!!",
    "I Got approved on Top.gg!!",
    "Maths is fun when you know what you are doing",
    "Made by tears and pure suffer",
    "Plotting equation of E",
    "Invite me to E thread pls",
    "Yo kid, wanna plot some graph?",
    "Open a market of math equations, you will make a fortune",
    "Can I buy the equation of infinity love?",
    "If Quantum PC came out tomorrow, I would be a goner",
    "RealityProgrammer is being trapped under a basement, writing new status",
    "Graph do be cool",
    "Stage 1: Graph, Stage 2: Graphics, Stage 3: 3D Rendering in Discord, Stage 4: Minecraft in discord",
    "Reality wants to do 3D on flat graph, but Denzven suk",
    "Your day is better than those who forgot the -y and only see straight vertical lines",
    "Reality is still waiting for actual multiple equation implementation",
    "What's the chance of generate an EDM via a single equation?",
    "Aeugh",
    "I literally has the power of curing deadly desease, but instead, I was forced to do graph",
    "Enlighten me with your graph",
    "Overflow go brrrrrrr",
    "I like your magic equation, nerdy boy",
    "Every beautiful graph start with x-y=0`",
    "Impress ur crush with your M A F F skill here",
    "Inequality when?",
    "Help I'm trapped in Backroom Level x-y=0",
    "Selling equation of world destruction...",
    "Powered by Procedural Equation Generator",
    "You thought this bot was powered by Matlab, but it was me, eval()",
    "Ah shit, here we plot again...",
    "Famous last words: \"What about 4D graph?\"",
    "Adding constant \"Aeugh\" with the value of 69",
    "Plot twist: There were no bot, everything was hand-drawn",
    "So where is Matrix?",
    "Reality is turning this status into a massive database of meme",
    "Yo man recommend me some good meme website. Me, and intellectual: GraphBots's status",
    "Thonking...",
    "Great graphing skill come with a great computing power",
    "Ignore the next status",
    "Ignore the last status",
    "If you are reading this, I need your help, I'm trapping under the eternal darkness, forced to write new status...",
    "Yes",
    "heh... Sugondese...",
    "Used by 99% of students who are having an exam",
    "Haha nerd",
    "Pain.mp3",
    "By the power of friendship, I plot this goddamn graph",
    "Nice character development",
    "To show you the power of this graphing bot, I kidnapped Reality",
    "Yeet",
    "I used to bad at math, then I took an equation to the knee",
    
    # HALLOWEEN
    "Muahahahahahhahahahahhahhahahha... Hi",
    "*Insert an Halloween themed quote here*",
    "Oh no! This is an carrot cake",
    "Well, the sign said \"Please take one.\", so I did, I take one bowl",
    "Today is the exception of your parents' \"Don't take candy from stranger\"",
    "I have prepared my whole years for this day. Since the last Halloween at least...",
    "something dangerous...",
    "and choking on glucose and fructose",
    "Guess whose dinner will consist of 99% sugar? RealityProgrammer, as usual...",
    "I can create meth from sugar... And I'll revolutionize it by mixing with water to create liquid meth",
    "Finally, I can take off this mask for one night",
    "Costume idea: Be yourself",
    "Happy Halloween",
    "Powered by: Candy",
    "\"Life is bootiful... isn't it\" - RealityProgrammer, literally everytime he found something... questionable...",
    "\"Which one?\", \"She did? Good for her\"", # TomSka quote "Magic Spoon", "Which one" = "Witch won"
    "ew... vegetable...",
    "Stay away from that house, they are giving healthy thing like veggie",
    "🎃 Spooky, scary skeletons Send shivers down your spine 🎃",
    "https://www.youtube.com/watch?v=-1dSY6ZuXEY",
    "It's that time of the year again.",
    "sorry i was busy snorting pumpkin sauce",
    "collecting ribs to make a xylophone",
    "im bored of graphing all day long.. lemme trick or treat!",
    "trick or treat?",
    "Spooookyyy",
    "October? more like.. Spooktober",
    
    # CHRISTMAS
    "and warming my butt...",
    "with smuggled fireworks",
    "\"My damn ass is freezing\"",
    "the temperature is -500 degree Celcius and dropping",
    "ABSOLUTE ZERO",
    "who need loved one if you love yourself right?",
    "internal class Crying",
    "InvalidOperationException were catch: Cannot delete module \"Loneliness\"",
    "can i have some candy from the halloween?",
    "Last Chrismast, I gave you my heart",
    "But the very next day, you yeet it away",
    "throwing egg on the one with lover.",
    "https://cdn.discordapp.com/attachments/812984732681764874/906386519277854770/250997094_210030764602164_6900415284391876328_n.png",
    "life is more than graphing, kid...",
    "eating snow...",
    "*Insert an Christmas themed quote here*",
    "RP is alone again but this time he got a chainsaw",
]
